### ISSUE TITLE
Supply credentials from env vars

### ISSUE THREAD

**Issue by callum** [andrewrk/node-s3-cli#11]
I'm looking at a way to deploy code through CI, but for that there needs to be an alternative way to supply creds. I currently get the error:

```
This utility needs a config file formatted the same as for s3cmd
```

What do you think to adding something that would allow:

```
AWS_ACCESS_KEY_ID=x AWS_SECRET_KEY=x s3cli
```

Great project by the way. The API is very clean.

**Comment by andrewrk** [comment]
That sounds good to me. Want to make a pull request?
