### ISSUE TITLE
Defaults to environment variables not in documentation

### ISSUE THREAD

**Issue by cameronmccord2** [andrewrk/node-s3-cli#15]
I spent a bit wondering why it wasn't reading my config file. After looking in the code I found it looks at your environment variables first. I work in multiple aws accounts and my environment variables were set up for a different account than the one I was accessing but all I got was 'Error: http status code 403'. Perhaps the documentation should say it looks to your environment variables first, even if you specify a config file using --config. Thanks!

**Comment by andrewrk** [comment]
Good point. I think this module should check config first, then env vars.

**Comment by andrewrk** [comment]
Alright really sorry about that. Now it prioritizes config over env vars, and I published the result as 0.13.0 with a minor bump in case anyone depended on the other behavior.
