### ISSUE TITLE
How to set Expires HTTP Header? (blank spaces)

### ISSUE THREAD

**Issue by caiocmpaes** [andrewrk/node-s3-cli#17]
How do I set the params if there are spaces in the VALUE param?

Docs:
--add-header=NAME:VALUE

I'm trying this (doesn't work):
s3-cli sync -P --add-header=Cache-Control:public,max-age=31536000 --add-header=Expires:'Fri, 18 Nov 2016 11:00:00 GMT' static/ s3://my-bucket/static/

Error: Unexpected key 'Expires:Fri, 18 Nov 2016 11:00' found in params

**Comment by andrewrk** [comment]
Try this:

```
s3-cli sync -P '--add-header=Cache-Control:public,max-age=31536000' '--add-header=Expires:Fri, 18 Nov 2016 11:00:00 GMT' static/ s3://my-bucket/static/
```

**Comment by caiocmpaes** [comment]
Thanks!

That worked.
