### ISSUE TITLE
Project specifc config

### ISSUE THREAD

**Issue by nickdima** [andrewrk/node-s3-cli#9]
I see that it looks for a config file in the user's home folder. What about project specific configs? Or maybe passing the credential from the command line. Is it possible?

**Comment by adambuczynski** [comment]
Sorry to dig this up, but does the `.s3cfg` file not support multiple entries for different keys?
This is implied by the `[default]` entry, e.g. can I add a `[something-else]` key and refer to that one somehow via s3-cli?
